---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install required packages
  apt:
    name:
      - openjdk-17-jdk
      - wget
      - gnupg
      - curl
    state: present
  become: true
- name: Add Jenkins GPG key
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg
  args:
    executable: /bin/bash
  become: true

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
    state: present
  become: true

- name: Update apt cache after adding repo
  apt:
    update_cache: yes
  become: true

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: true

- name: Ensure Jenkins is started
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: Wait for Jenkins to start
  wait_for:
    port: 8080
    delay: 10
    timeout: 120

- name: Get initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_admin_password
  changed_when: false
  become: true
